### ISSUE TITLE
.\worlds\aardwolf.mcl contains an invalid path

### ISSUE THREAD

**Issue by CloudCuddler** [fiendish/aardwolfclientpackage#222]
when i downloaded aardwolf mushclient i got this message: .\worlds\aardwolf.mcl contains an invalid path.
i didnt get the black window explaining how to move windows 'n stuff.
how to fix this?

**Comment by fiendish** [comment]
A couple of things come to mind as possible culprits:

1)

Strange file access errors can happen if you have put the mushclient folder
in a UAC "protected" location (e.g. Program Files) instead of an
unprotected place.

See: http://www.mushclient.com/forum/bbshowpost.php?bbsubject_id=11845

2)

You mention previous behavior which suggests to me that you're moving your
world file from one install to another. Can you open up your aardwolf.mcl
file and make sure that any file paths (plugins, etc) in it are still valid?
You can paste the whole file here if you don't know where to look, just
make sure to delete the password field from it first.

**Comment by CloudCuddler** [comment]
i checked and it was not in program files.
here is a link to aardwolf.mcl i extracted it into a folder
https://www.dropbox.com/sh/4m6lfyin64056fg/AAAurzXJ6HuJ4KTOzsEqDRgfa?dl=0

**Comment by fiendish** [comment]
Well I downloaded the whole folder you posted (https://www.dropbox.com/sh/4m6lfyin64056fg/AADUPclq3S73Xy4KGwQ0JTAPa/aardwolfclientpackage-MUSHclient/MUSHclient?dl=0) and it runs fine for me.

So I'm back to still thinking that you might have it in a bad location. Where exactly do you have it on your computer?

**Comment by CloudCuddler** [comment]
it is on my desktop

**Comment by CloudCuddler** [comment]
i tried running it as administrator and that worked. thx for the help though! ;)

**Comment by fiendish** [comment]
I think in desktop it shouldn't need to be run as admin... But I seem to be
wrong at least in this instance. Windows file permissions are wonky stuff.
Glad it's working.
