### ISSUE TITLE
Rotate Map funtionality - Mapper plugin

### ISSUE THREAD

**Issue by droslean** [fiendish/aardwolfclientpackage#254]
It would be good if we have this ability, to rotate the map in the mapper plugin

**Comment by fiendish** [comment]
It's possible, but why? Aardwolf doesn't rotate with directional perspective. N is always N, S is always S.

**Comment by droslean** [comment]
There are many people that think the map differently. For example I think of it inverted by 180 degrees.  So I can't use the mapper plugin because it is confusing me. I met many people that think the map differently as well. Since the rotate functionality can be done I can't see why not.

**Comment by droslean** [comment]
@fiendish Is there any plans to add this functionality to the map?

**Comment by fiendish** [comment]
Yes, but it will take some time to get to it. If you need it very soon,
maybe someone on Aardwolf would be willing to help you code it and make a
GitHub pull request.


On Feb 24, 2018 1:01 PM, "Nikolaos Leandros Moraitis" <
notifications@github.com> wrote:

@fiendish <https://github.com/fiendish> Is there any plans to add this
functionality to the map?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/fiendish/aardwolfclientpackage/issues/254#issuecomment-368247009>,
or mute the thread
