### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by ph1234k** [fiendish/aardwolfclientpackage#289]
This is the second time my map has been partially corrupt and none of my DB backups have the map info either.
On r2052

Sadly, it's bad enough that I am not going to play the game for a while. Having to re-map everything again is terrible. 

I have no clue what may be causing it. 
I also have been using some plugins (Pwars plugin manager, winklewinkle spellup and winklegold s&d)

**Comment by ph1234k** [comment]
Also, S&D a;so has the WW Mapper Extender plugin as a dependency (Sorry, edit button not working, probably cause I need to update my browser)

**Comment by fiendish** [comment]
> This is the second time

That's unfortunate, but it's only the first time you're telling me about it here.

> (Sorry, edit button not working, probably cause I need to update my browser)

If the edit button isn't working because your browser is broken, what else on your computer isn't working for similar reasons?

If there's a problem with the mapper backup mechanism, then I need a proper bug report for that specifically. I can't help with problems that may be caused by someone else's plugins doing bad things in my database file.

**Comment by fiendish** [comment]
> Also, S&D a;so has the WW Mapper Extender plugin as a dependency (Sorry, edit button not working, probably cause I need to update my browser)

If the edit button isn't working because your browser is broken, what else on your computer isn't working for similar reasons?
